application: drugdictionary
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /ajax.json
  script: src.ajax.application
- url: /callback
  script: src.login.application
- url: /login.json
  script: src.login.application
  
- url: /js
  static_dir: html/js
- url: /
  static_files: html/index.html
  upload: html/index.html
- url: /(.+.html)
  static_files: html/\1
  upload: html/.*
- url: /(.+.(gif|ico))
  static_files: html/img/\1
  upload: html/img/.*
- url: /css/(.+.css)
  static_files: html/css/\1
  upload: html/css/.*